ALTER TABLE scrape_jobs
    ADD COLUMN IF NOT EXISTS current_stage TEXT NOT NULL DEFAULT 'DISCOVERY',
    ADD COLUMN IF NOT EXISTS max_depth INTEGER NOT NULL DEFAULT 3,
    ADD COLUMN IF NOT EXISTS max_pages INTEGER NOT NULL DEFAULT 50,
    ADD COLUMN IF NOT EXISTS pages_visited INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pages_discovered INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS tender_pages_found INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS tenders_extracted INTEGER NOT NULL DEFAULT 0;

ALTER TABLE tenders
    ADD COLUMN IF NOT EXISTS page_type TEXT NOT NULL DEFAULT 'TENDER_DETAIL',
    ADD COLUMN IF NOT EXISTS confidence_score DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS confidence_signals JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS discovery_url TEXT,
    ADD COLUMN IF NOT EXISTS discovery_depth INTEGER,
    ADD COLUMN IF NOT EXISTS discovery_path JSONB NOT NULL DEFAULT '[]'::jsonb;
